version = "1.6.0"

[releases."1.2.1"]
entries = ["patch-01khkj64ppmws0zfsp3jszp5dp.md"]

[releases."1.2.2"]
entries = ["patch-01khkkwqy6r24pj25k72bp5jec.md"]

[releases."1.3.0"]
entries = ["minor-01khkkxdphyqfypxya1vjrs94g.md"]

[releases."1.4.0"]
entries = ["minor-01khm51jhnzw66am1k2sqj3s5w.md"]

[releases."1.4.1"]
entries = ["patch-01khp50xsyd47awswyph8bwa31.md"]

[releases."1.4.2"]
entries = ["patch-01khv1ya5cxbd9av0mznpv3pe9.md"]

[releases."1.4.3"]
entries = ["patch-01kj38wz92k71p6cz1r85jgye0.md"]

[releases."1.4.4"]
entries = ["patch-01kj376pc14qq4aw8jzby9m8bk.md"]

[releases."1.4.5"]
entries = [
    "patch-01kj3a82xept7aw2yb2dtkzefk.md",
    "patch-01kj3dnnk0dbxrjpsfcxkk697e.md",
]

[releases."1.4.6"]
entries = [
    "patch-01kj3p0tgck8yhrjgk4x3fb5fa.md",
    "patch-01kj3r2xz0yw7dtzzzz7q0qsne.md",
]
release_group = "rg-01kj3sy053a17nnhq71ftm51bn"

[releases."1.5.0"]
entries = ["minor-01kk44gh4hy49mssbgmpxvvh2p.md"]
release_group = "rg-01kk45amd56wgapk71xcjt3j6n"

[releases."1.6.0"]
entries = ["minor-01kkeb7h5pa6kv31jw4tspshnj.md"]
release_group = "rg-01kkebv5cbkbrrjx0wjmsh61mw"

[[release_groups]]
id = "rg-01kj3sy053a17nnhq71ftm51bn"
workspaces = ["root"]

[release_groups.before]
root = "1.4.5"

[release_groups.after]
root = "1.4.6"

[[release_groups]]
id = "rg-01kk45amd56wgapk71xcjt3j6n"
workspaces = ["root"]

[release_groups.before]
root = "1.4.6"

[release_groups.after]
root = "1.5.0"

[[release_groups]]
id = "rg-01kkebv5cbkbrrjx0wjmsh61mw"
workspaces = ["root"]

[release_groups.before]
root = "1.5.0"

[release_groups.after]
root = "1.6.0"
